version: '3.8'

services:
  # gateway-controller:
  #   build:
  #     context: ./gateway-controller
  #     dockerfile: Dockerfile
  #   container_name: gateway-controller
  #   ports:
  #     - "9090:9090"   # REST API
  #     - "18000:18000" # xDS gRPC
  #   environment:
  #     - LOG_LEVEL=info
  #     - DB_PATH=/data/gateway-controller.db
  #     - API_PORT=9090
  #     - XDS_PORT=18000
  #   volumes:
  #     - controller-data:/data
  #   networks:
  #     - gateway-network
  #   healthcheck:
  #     test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/health"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 10s

  router:
    build:
      context: ./router
      dockerfile: Dockerfile
    container_name: router
    ports:
      - "8080:8080"   # HTTP traffic
      - "9901:9901"   # Envoy admin
    environment:
      - XDS_SERVER_HOST=host.docker.internal
      - XDS_SERVER_PORT=18000
    # depends_on:
    #   gateway-controller:
    #     condition: service_healthy
    networks:
      - gateway-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9901/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  sample-backend:
    image: renukafernando/request-info:latest
    container_name: sample-backend
    ports:
      - "3000:3000"
    command: ["-addr", ":3000", "-pretty"]
    networks:
      - gateway-network

volumes:
  controller-data:
    driver: local

networks:
  gateway-network:
    driver: bridge
