/*
 *  Copyright (c) 2026, WSO2 LLC. (http://www.wso2.org) All Rights Reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

package service

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"time"

	"platform-api/src/config"
	"platform-api/src/internal/constants"
	"platform-api/src/internal/dto"
	"platform-api/src/internal/model"
	"platform-api/src/internal/repository"

	"github.com/google/uuid"
	commonconstants "github.com/wso2/api-platform/common/constants"
	"gopkg.in/yaml.v3"
)

// ImportContext carries everything a per-kind importer needs to create or update
// an artifact pushed from a data-plane gateway.
type ImportContext struct {
	OrgID        string
	GatewayID    string
	SyncMetadata bool // whether this gateway owns the CP's metadata working copy

	// ID is the control-plane artifact UUID: reused when the artifact already exists
	// (matched by handle), otherwise freshly generated by the orchestrator. It is NOT
	// the data-plane UUID — the CP owns its own identifier.
	ID string
	// DPID is the data-plane (gateway) artifact UUID as pushed. It is informational
	// (logging/traceability) and is never used as the CP artifact UUID.
	DPID          string
	Configuration dto.ArtifactImportConfig
	Status        string // deployed|pending|failed|undeployed (as pushed)
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeployedAt    *time.Time
	Properties    map[string]interface{}

	ProjectName string // metadata.project (may be empty)
	ProjectID   string // resolved project UUID (empty for org-level kinds)

	// Existing is the already-stored artifacts-table row keyed by ID, or nil if new.
	// It is nil for organization-level kinds that are not backed by the artifacts
	// table (e.g. LLM Provider Templates); those importers resolve existence themselves.
	Existing *model.Artifact
}

// ImportResult is returned by an importer describing the persisted artifact.
type ImportResult struct {
	ID              string
	DeployedVersion string
	// Deployable indicates the artifact has a per-gateway deployment lifecycle and
	// therefore a deployment record + status row should be written by the orchestrator.
	Deployable bool
}

// GatewayArtifactImporter is the contract every artifact kind implements so the
// DP->CP import flow stays generic and open to new kinds.
type GatewayArtifactImporter interface {
	// Kind returns the artifact kind string this importer handles (see constants).
	Kind() string
	// RequiresProject reports whether metadata.project must be present and resolvable.
	RequiresProject() bool
	// Import creates or updates the artifact and returns the persisted result.
	Import(ctx *ImportContext) (*ImportResult, error)
}

// ArtifactImportService resolves the correct importer for a pushed artifact and
// runs the shared pre/post processing (gateway auth, project resolution,
// deployment/status persistence).
type ArtifactImportService struct {
	importers      map[string]GatewayArtifactImporter
	gatewayRepo    repository.GatewayRepository
	projectRepo    repository.ProjectRepository
	artifactRepo   repository.ArtifactRepository
	deploymentRepo repository.DeploymentRepository
	apiRepo        repository.APIRepository
	cfg            *config.Server
	slogger        *slog.Logger
}

// NewArtifactImportService builds the import service and registers an importer for
// every supported artifact kind. Adding a new kind is a matter of registering a
// new importer here — no changes to the endpoint or orchestrator are required.
func NewArtifactImportService(
	apiRepo repository.APIRepository,
	providerRepo repository.LLMProviderRepository,
	templateRepo repository.LLMProviderTemplateRepository,
	proxyRepo repository.LLMProxyRepository,
	mcpProxyRepo repository.MCPProxyRepository,
	artifactRepo repository.ArtifactRepository,
	deploymentRepo repository.DeploymentRepository,
	gatewayRepo repository.GatewayRepository,
	projectRepo repository.ProjectRepository,
	cfg *config.Server,
	slogger *slog.Logger,
) *ArtifactImportService {
	s := &ArtifactImportService{
		gatewayRepo:    gatewayRepo,
		projectRepo:    projectRepo,
		artifactRepo:   artifactRepo,
		deploymentRepo: deploymentRepo,
		apiRepo:        apiRepo,
		cfg:            cfg,
		slogger:        slogger,
	}
	s.importers = map[string]GatewayArtifactImporter{
		constants.RestApi:             newRestAPIImporter(apiRepo, artifactRepo),
		constants.LLMProvider:         newLLMProviderImporter(providerRepo, templateRepo, artifactRepo),
		constants.LLMProviderTemplate: newLLMProviderTemplateImporter(templateRepo),
		constants.LLMProxy:            newLLMProxyImporter(proxyRepo, artifactRepo),
		constants.MCPProxy:            newMCPProxyImporter(mcpProxyRepo, artifactRepo),
	}
	return s
}

// Import is the entry point for the DP->CP push. It authenticates the gateway,
// resolves the importer by kind, resolves the project when required, delegates to
// the importer, and persists deployment/status for deployable kinds.
func (s *ArtifactImportService) Import(orgID, gatewayID string, req dto.ImportGatewayArtifactRequest) (*dto.ImportGatewayArtifactResponse, error) {
	if orgID == "" || gatewayID == "" || req.ID == "" {
		return nil, constants.ErrInvalidInput
	}

	kind := req.Configuration.Kind
	importer, ok := s.importers[kind]
	if !ok {
		s.slogger.Warn("Unsupported artifact kind for gateway import", "kind", kind, "artifactId", req.ID)
		return nil, fmt.Errorf("%w: %s", constants.ErrArtifactInvalidKind, kind)
	}

	// Verify the gateway exists, belongs to the org, and read its sync_metadata flag.
	gateway, err := s.gatewayRepo.GetByUUID(gatewayID)
	if err != nil {
		return nil, fmt.Errorf("failed to get gateway: %w", err)
	}
	if gateway == nil || gateway.OrganizationID != orgID {
		return nil, constants.ErrGatewayNotFound
	}

	// An "undeployed" push means the artifact was deleted from the gateway. The control
	// plane keeps the artifact but marks it undeployed on this gateway — it does not
	// delete it, create a new deployment, or touch the metadata. A later "deployed"
	// push (re-deploy) takes the normal path below, creating a fresh deployment and
	// updating metadata when this gateway owns it (sync_metadata).
	if req.Status == importStatusUndeployed {
		return s.handleUndeploy(orgID, gatewayID, req)
	}

	ictx := &ImportContext{
		OrgID:         orgID,
		GatewayID:     gatewayID,
		SyncMetadata:  gateway.SyncMetadata,
		DPID:          req.ID,
		Configuration: req.Configuration,
		Status:        req.Status,
		CreatedAt:     req.CreatedAt,
		UpdatedAt:     req.UpdatedAt,
		DeployedAt:    req.DeployedAt,
		Properties:    req.Properties,
		ProjectName:   resolveImportProject(req.Configuration.Metadata),
	}

	// Resolve project for project-scoped kinds. Org-level kinds ignore the project.
	if importer.RequiresProject() {
		if ictx.ProjectName == "" {
			// The gateway must always supply the project (as a metadata label) for
			// project-scoped kinds; a push without one is a contract violation.
			s.slogger.Error("Project is required for gateway-imported artifact but was not provided",
				"kind", kind, "artifactId", req.ID)
			return nil, fmt.Errorf("%w: project is required for kind %s", constants.ErrInvalidInput, kind)
		}
		project, err := s.projectRepo.GetProjectByNameAndOrgID(ictx.ProjectName, orgID)
		if err != nil {
			return nil, fmt.Errorf("failed to resolve project %q: %w", ictx.ProjectName, err)
		}
		if project == nil {
			// The project was provided but does not exist in this organization. Reject the
			// import with ErrProjectNotFound (the project is never created or defaulted);
			// the artifact is not created in the control plane.
			s.slogger.Error("Project is not available in the organization; gateway artifact not imported",
				"kind", kind, "artifactId", req.ID, "project", ictx.ProjectName, "orgId", orgID)
			return nil, fmt.Errorf("%w: project %q does not exist in org %q", constants.ErrProjectNotFound, ictx.ProjectName, orgID)
		}
		ictx.ProjectID = project.ID
	}

	// The control plane owns the artifact UUID; it does NOT reuse the data-plane UUID
	// (the gateway mints a fresh one whenever the artifact is recreated). Match an
	// already-imported artifact by its handle, which is unique per organization and
	// stable across delete/recreate. When found, reuse its CP UUID (so a recreate
	// re-attaches to the same artifact and only adds a new deployment); otherwise mint
	// a new CP UUID. Org-level kinds (e.g. templates) are not in the artifacts table —
	// GetByHandle returns nil and the importer resolves existence itself.
	handle := importHandle(ictx)
	existing, err := s.artifactRepo.GetByHandle(handle, orgID)
	if err != nil {
		return nil, fmt.Errorf("failed to look up existing artifact: %w", err)
	}
	if existing != nil {
		// Guard against handle reuse across kinds.
		if existing.Kind != kind {
			return nil, fmt.Errorf("%w: artifact %q already exists with kind %s", constants.ErrArtifactExists, handle, existing.Kind)
		}
		ictx.ID = existing.UUID
		ictx.Existing = existing
	} else {
		ictx.ID = uuid.NewString()
	}

	result, err := importer.Import(ictx)
	if err != nil {
		return nil, err
	}

	// Persist deployment + status for deployable kinds (everything except templates).
	if result.Deployable {
		if err := s.writeDeployment(ictx, result.ID); err != nil {
			return nil, err
		}
	}

	return &dto.ImportGatewayArtifactResponse{
		ID:              result.ID,
		Status:          req.Status,
		Origin:          constants.OriginDP,
		CreatedAt:       req.CreatedAt,
		UpdatedAt:       req.UpdatedAt,
		DeployedAt:      req.DeployedAt,
		DeployedVersion: result.DeployedVersion,
	}, nil
}

// writeDeployment records the immutable deployment artifact, upserts the current
// deployment_status row, and ensures the artifact<->gateway association exists.
func (s *ArtifactImportService) writeDeployment(ictx *ImportContext, artifactUUID string) error {
	content, err := yaml.Marshal(ictx.Configuration)
	if err != nil {
		return fmt.Errorf("failed to serialize deployment content: %w", err)
	}

	if s.cfg.Deployments.MaxPerAPIGateway < 1 {
		return fmt.Errorf("MaxPerAPIGateway limit config must be at least 1, got %d", s.cfg.Deployments.MaxPerAPIGateway)
	}
	hardLimit := s.cfg.Deployments.MaxPerAPIGateway + constants.DeploymentLimitBuffer

	status := mapDeploymentStatus(ictx.Status)
	now := time.Now()
	deployment := &model.Deployment{
		Name:           fmt.Sprintf("deployment-%d", now.Unix()),
		ArtifactID:     artifactUUID,
		GatewayID:      ictx.GatewayID,
		OrganizationID: ictx.OrgID,
		Content:        content,
		Status:         &status,
		CreatedAt:      now,
	}
	if err := s.deploymentRepo.CreateWithLimitEnforcement(deployment, hardLimit); err != nil {
		return fmt.Errorf("failed to create deployment record: %w", err)
	}

	// Ensure the gateway association exists so the artifact is listed against the
	// gateway in the control plane. association_mappings is generic across kinds.
	assocs, err := s.apiRepo.GetAPIAssociations(artifactUUID, constants.AssociationTypeGateway, ictx.OrgID)
	if err != nil {
		return fmt.Errorf("failed to check artifact-gateway associations: %w", err)
	}
	associated := false
	for _, a := range assocs {
		if a.ResourceID == ictx.GatewayID {
			associated = true
			break
		}
	}
	if !associated {
		now := time.Now()
		if err := s.apiRepo.CreateAPIAssociation(&model.APIAssociation{
			ArtifactID:      artifactUUID,
			OrganizationID:  ictx.OrgID,
			ResourceID:      ictx.GatewayID,
			AssociationType: constants.AssociationTypeGateway,
			CreatedAt:       now,
			UpdatedAt:       now,
		}); err != nil {
			return fmt.Errorf("failed to create artifact-gateway association: %w", err)
		}
	}
	return nil
}

// resolveImportProject extracts the project identifier from the k8s-shaped metadata.
// The project is identified by the domain-prefixed project-id annotation.
func resolveImportProject(md dto.ArtifactImportMetadata) string {
	return md.Annotations[commonconstants.AnnotationProjectID]
}

// shouldWriteMetadata decides whether an importer may write artifact metadata for
// this push. Gateway-specific data (upstreams) is always written by the importer.
//
//   - new artifact          -> write metadata (create with origin DP)
//   - existing, origin CP    -> do NOT write metadata (the CP owns this artifact)
//   - existing, origin DP    -> write metadata only if this gateway syncs metadata
func shouldWriteMetadata(existing *model.Artifact, syncMetadata bool) bool {
	if existing == nil {
		return true
	}
	if existing.Origin == constants.OriginCP {
		return false
	}
	return syncMetadata
}

// Pushed artifact status strings.
const (
	importStatusDeployed   = "deployed"
	importStatusPending    = "pending"
	importStatusFailed     = "failed"
	importStatusUndeployed = "undeployed"
)

// mapDeploymentStatus maps a pushed status string to a deployment_status value.
func mapDeploymentStatus(status string) model.DeploymentStatus {
	switch status {
	case importStatusDeployed:
		return model.DeploymentStatusDeployed
	case importStatusPending:
		return model.DeploymentStatusDeploying
	case importStatusFailed:
		return model.DeploymentStatusFailed
	case importStatusUndeployed:
		return model.DeploymentStatusUndeployed
	default:
		return model.DeploymentStatusDeployed
	}
}

// handleUndeploy processes an "undeployed" push (the artifact was deleted from the
// gateway). It marks the artifact undeployed on this gateway and keeps it: it never
// deletes the artifact, never creates a new deployment record, and never alters the
// metadata. If the artifact (or its deployment status row) is unknown it is a no-op.
func (s *ArtifactImportService) handleUndeploy(orgID, gatewayID string, req dto.ImportGatewayArtifactRequest) (*dto.ImportGatewayArtifactResponse, error) {
	resp := &dto.ImportGatewayArtifactResponse{
		ID:         req.ID,
		Status:     req.Status,
		Origin:     constants.OriginDP,
		CreatedAt:  req.CreatedAt,
		UpdatedAt:  req.UpdatedAt,
		DeployedAt: req.DeployedAt,
	}

	// Match by handle: the data-plane UUID is regenerated on recreate and is never the
	// CP UUID, so the stable per-org handle is the lookup key.
	handle := req.Configuration.Metadata.Name
	existing, err := s.artifactRepo.GetByHandle(handle, orgID)
	if err != nil {
		return nil, fmt.Errorf("failed to look up artifact for undeploy: %w", err)
	}
	if existing == nil {
		// Unknown artifact (e.g. an org-level template, or never imported). Nothing to
		// undeploy; the artifact is not created on an undeploy push.
		s.slogger.Warn("Undeploy push for unknown artifact; ignoring",
			"handle", handle, "dpId", req.ID, "kind", req.Configuration.Kind, "gatewayId", gatewayID)
		return resp, nil
	}
	// Echo the control-plane UUID back to the gateway.
	resp.ID = existing.UUID
	resp.DeployedVersion = existing.Version

	deploymentID, status, _, err := s.deploymentRepo.GetStatus(existing.UUID, orgID, gatewayID)
	if err != nil {
		return nil, fmt.Errorf("failed to get deployment status for undeploy: %w", err)
	}
	if deploymentID == "" {
		s.slogger.Warn("Undeploy push but no deployment status exists for artifact on gateway; nothing to undeploy",
			"artifactId", existing.UUID, "gatewayId", gatewayID)
		return resp, nil
	}
	if status == model.DeploymentStatusUndeployed {
		return resp, nil // already undeployed; idempotent
	}
	if _, err := s.deploymentRepo.SetCurrentWithDetails(
		existing.UUID, orgID, gatewayID, deploymentID, model.DeploymentStatusUndeployed, "", nil, ""); err != nil {
		return nil, fmt.Errorf("failed to mark artifact undeployed: %w", err)
	}
	s.slogger.Info("Marked gateway-deleted artifact as undeployed in the control plane",
		"artifactId", existing.UUID, "gatewayId", gatewayID)
	return resp, nil
}

// importVersion resolves the artifact version from the CR spec (version lives in the
// spec, not the k8s metadata), defaulting to "1.0.0" when absent.
func importVersion(ctx *ImportContext) string {
	if v := specString(ctx.Configuration.Spec, "version"); v != "" {
		return v
	}
	return "1.0.0"
}

// importHandle returns the URL-safe identifier for the artifact. metadata.name is
// treated as the handle (identifier) in the k8s-shaped descriptor.
func importHandle(ctx *ImportContext) string {
	return ctx.Configuration.Metadata.Name
}

// importDisplayName returns the human-friendly name, falling back to the handle.
func importDisplayName(ctx *ImportContext) string {
	if dn := specString(ctx.Configuration.Spec, "displayName"); dn != "" {
		return dn
	}
	return ctx.Configuration.Metadata.Name
}

// specString safely extracts a string value from the generic spec map.
func specString(spec map[string]interface{}, key string) string {
	if spec == nil {
		return ""
	}
	if v, ok := spec[key].(string); ok {
		return v
	}
	return ""
}

// specProviderHandle extracts the provider handle from a proxy CR spec.
// The gateway encodes the provider as an object ({id: <handle>, auth: ...}) rather
// than a plain string, so a simple cast on spec["provider"] is not enough.
func specProviderHandle(spec map[string]interface{}) string {
	if spec == nil {
		return ""
	}
	provider, ok := spec["provider"].(map[string]interface{})
	if !ok {
		return ""
	}
	id, _ := provider["id"].(string)
	return id
}

// specWithout returns a shallow copy of spec with the named key omitted.
// The original map is never modified.
func specWithout(spec map[string]interface{}, key string) map[string]interface{} {
	if spec == nil {
		return nil
	}
	out := make(map[string]interface{}, len(spec))
	for k, v := range spec {
		if k != key {
			out[k] = v
		}
	}
	return out
}

// decodeSpec re-marshals the generic spec map into a kind-specific struct via JSON.
// Unknown fields are ignored, matching fields are populated.
func decodeSpec(spec map[string]interface{}, out interface{}) error {
	if len(spec) == 0 {
		return nil
	}
	b, err := json.Marshal(spec)
	if err != nil {
		return fmt.Errorf("failed to marshal spec: %w", err)
	}
	if err := json.Unmarshal(b, out); err != nil {
		return fmt.Errorf("failed to decode spec: %w", err)
	}
	return nil
}
